name: Leenloket
description: "Lend, use and return"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:

  # -- LEENLOKET PACKAGES
  fan_carousel_image_slider: ^0.1.2
  flutter_native_splash: ^2.3.6

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_profile_picture: ^2.0.0

  # -- FIREBASE PACKAES
  firebase_core: ^2.23.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.15.0
  firebase_database: ^10.3.6
  date_field: ^3.0.5
  flutter_datetime_picker: ^1.5.1
  firebase_storage: ^11.5.5
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  rive: ^0.12.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon/icon.png"

# Splash screen configuration
flutter_native_splash:
  color: "#d7263d"
  image: assets/images/logo.png
  android: true
  ios: true


flutter:
# -----------------------------------------------
#   FLUTTER CONFIGURATION
# -----------------------------------------------
#
# The following section is specific to Flutter.
#

  uses-material-design: true

# -----------------------------------------------
#   LOCALIZATION
# -----------------------------------------------
#
# Localization configuration. This will generate the necessary files for localization.
#
# For more information, see: https://flutter.dev/docs/development/accessibility-and-localization/internationalization
#

  # Enable generation of localized Strings from arb files.
  generate: true


# -----------------------------------------------
#   ASSETS
# -----------------------------------------------
#
# Assets that are using within the app. Each asset should have a key and a list of assets.
#


  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/rive/


# -----------------------------------------------
#   FONTS
# -----------------------------------------------
#
# Fonts that are using within the app. Each font should have a family entry and each family 
# should have a list of fonts.
#
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
