// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:1039865739935:web:ca8741cde6c9a2e32080aa',
    messagingSenderId: '1039865739935',
    projectId: 'tue-leenloket',
    authDomain: 'tue-leenloket.firebaseapp.com',
    databaseURL: 'https://tue-leenloket-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tue-leenloket.appspot.com',
    measurementId: 'G-FBLNEFNWZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:1039865739935:android:bc6cd49534a74add2080aa',
    messagingSenderId: '1039865739935',
    projectId: 'tue-leenloket',
    databaseURL: 'https://tue-leenloket-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tue-leenloket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:1039865739935:ios:a7828e4bd41d95a82080aa',
    messagingSenderId: '1039865739935',
    projectId: 'tue-leenloket',
    databaseURL: 'https://tue-leenloket-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tue-leenloket.appspot.com',
    androidClientId: '1039865739935-7nol9u7gjd36kgn09hejejm3h586vu6p.apps.googleusercontent.com',
    iosClientId: '1039865739935-n0cbu7p4prevhqgd14k182gse2q665ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.leenloketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:1039865739935:ios:5b30598c770e56372080aa',
    messagingSenderId: '1039865739935',
    projectId: 'tue-leenloket',
    databaseURL: 'https://tue-leenloket-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tue-leenloket.appspot.com',
    androidClientId: '1039865739935-7nol9u7gjd36kgn09hejejm3h586vu6p.apps.googleusercontent.com',
    iosClientId: '1039865739935-igv9545r9e7l3sf5vjjq3qctsrn755mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.leenloketApp.RunnerTests',
  );
}
