// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl4ViK8bFd2QZdCn6h_CP6qrnHw_Jpz0g',
    appId: '1:1039865739935:android:bc6cd49534a74add2080aa',
    messagingSenderId: '1039865739935',
    projectId: 'tue-leenloket',
    databaseURL: 'https://tue-leenloket-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tue-leenloket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT51KwrpWonVij2fSSBLLjpUu92IeOx_Q',
    appId: '1:1039865739935:ios:a7828e4bd41d95a82080aa',
    messagingSenderId: '1039865739935',
    projectId: 'tue-leenloket',
    databaseURL: 'https://tue-leenloket-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tue-leenloket.appspot.com',
    iosBundleId: 'com.example.leenloketApp',
  );
}
